### PR TITLE
fix main file path, change to relative path

### PR DESCRIPTION
**Pull request by PMCorbett**
I'm having an issue where this package is working great in reality, but causing eslint and test suites to fail because they cannot resolve the main entry point to the package.

I think the main entry point is meant to be relative to the package directory, rather than absolute.

Thanks very much for this great package

### CODE REVIEW

**Review by tjindapitak — APPROVED** [review]
my bad :(
thanks :)

**Comment by PMCorbett** [comment]
Excellent, thanks mate. Do you know when this might be released? 🙏

**Comment by tjindapitak** [comment]
I will release it in an hour

**Comment by tjindapitak** [comment]
v.1.2.2 is released
thanks for contributing 👍

**Pull request merged**
